version: 2
updates:
  # Enable version updates for npm dependencies
  # Configured for letstalk-webapp React/Vite project
  # Schedule: Daily at 00:00 SAST (22:00 UTC previous day)
  # Note: Dependabot doesn't support "every 2 days", so using daily with limited PRs
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "22:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Allow Dependabot to rebase PRs automatically
    rebase-strategy: "auto"
    # Ignore specific dependencies that should be updated manually
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    # Group minor and patch updates
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      aws-amplify:
        patterns:
          - "@aws-amplify/*"
          - "aws-amplify"
      material-ui:
        patterns:
          - "@mui/*"
          - "@emotion/*"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "eslint*"
          - "prettier"
          - "jest*"
          - "babel*"
          - "@babel/*"
      ui-icons:
        patterns:
          - "@fortawesome/*"
      testing:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "identity-obj-proxy"
      redux:
        patterns:
          - "@reduxjs/*"
          - "react-redux"
      bootstrap:
        patterns:
          - "bootstrap"
      router:
        patterns:
          - "react-router*"
    # Version update strategy
    versioning-strategy: "increase"
    # Target branch for PRs
    target-branch: "develop"

  # Enable version updates for GitHub Actions
  # Schedule: Daily at 00:00 SAST (22:00 UTC previous day)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "22:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "🔧"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
